# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hevy < Formula
  desc "CLI to manage workouts on Hevy. Includes a skill for ai agents to manage workouts for you."
  homepage ""
  version "0.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Dor256/hevy-cli/releases/download/v0.0.4/hevy-cli_0.0.4_darwin_amd64.tar.gz"
      sha256 "3e7aa7ab71d5c9c627630e2c7098c27a15ef93c1834260a235bf82e1a2a5d606"

      define_method(:install) do
        bin.install "hevy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Dor256/hevy-cli/releases/download/v0.0.4/hevy-cli_0.0.4_darwin_arm64.tar.gz"
      sha256 "3e03f2410eeebd45ed49e6fd808a206752e1bf85f599941d3c482e5bbb53086b"

      define_method(:install) do
        bin.install "hevy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dor256/hevy-cli/releases/download/v0.0.4/hevy-cli_0.0.4_linux_amd64.tar.gz"
      sha256 "bda0d0f5479ed75ffae328aa3f32739cbac1ce11cae83475fd3b94204f7796d2"
      define_method(:install) do
        bin.install "hevy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dor256/hevy-cli/releases/download/v0.0.4/hevy-cli_0.0.4_linux_arm64.tar.gz"
      sha256 "f3d85232ddc26f11a8b8540e42c04e8baed9b48d909720d8d5b677ef34623056"
      define_method(:install) do
        bin.install "hevy"
      end
    end
  end
end
