# This file was generated by GoReleaser. DO NOT EDIT.
cask "hevy" do
  name "hevy"
  desc "CLI to manage workouts on Hevy. Includes a skill for ai agents to manage workouts for you."
  homepage ""
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hevy"

  on_macos do
    on_intel do
      url "https://github.com/Dor256/hevy-cli/releases/download/v#{version}/hevy-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "bff2a97580a8ddb07291a7a02067f7c110d8e0a463d98b0cd1b2e8da9e8ecb20"
    end
    on_arm do
      url "https://github.com/Dor256/hevy-cli/releases/download/v#{version}/hevy-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "7ff2f56720f33f422bf1bdc83b403bd6d573b2609d1ba7f006ae941db957ddcc"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Dor256/hevy-cli/releases/download/v#{version}/hevy-cli_#{version}_linux_amd64.tar.gz"
      sha256 "0b3a9bdbd08d4b45535703d60f39cc06c99d51c8b163f6da476c3b77b7714aea"
    end
    on_arm do
      url "https://github.com/Dor256/hevy-cli/releases/download/v#{version}/hevy-cli_#{version}_linux_arm64.tar.gz"
      sha256 "8d1e8fc3e8e3f1dd3e94fd60ae3a6b36d9fa6e77ebcef78db37da020fa24213e"
    end
  end

  # No zap stanza required
end
